In [4]:
import os
print("Files in this folder:")
print(os.listdir())

Files in this folder:
['.anaconda', '.conda', '.condarc', '.continuum', '.ipynb_checkpoints', '.ipython', '.jupyter', '.matplotlib', '.virtual_documents', '.vscode', '01_data_cleaning_eda.ipynb', '01_data_understanding.ipynb', '3D Objects', 'anaconda3', 'anaconda_projects', 'AppData', 'Application Data', 'bich.py', 'BullseyeCoverageError.txt', 'Contacts', 'Cookies', 'Desktop', 'Documents', 'Downloads', 'dva project 2 sample.ipynb', 'Favorites', 'hes.ipynb', 'IntelGraphicsProfiles', 'Links', 'Local Settings', 'Microsoft', 'MicrosoftEdgeBackups', 'mod', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{94f431cb-13f9-11f0-9cd6-ef2ce1de21b4}.TxR.0.regtrans-ms', 'NTUSER.DAT{94f431cb-13f9-11f0-9cd6-ef2ce1de21b4}.TxR.1.regtrans-ms', 'NTUSER.DAT{94f431cb-13f9-11f0-9cd6-ef2ce1de21b4}.TxR.2.regtrans-ms', 'NTUSER.DAT{94f431cb-13f9-11f0-9cd6-ef2ce1de21b4}.TxR.blf', 'NTUSER.DAT{94f431cc-13f9-11f0-9cd6-ef2ce1de21b4}.TM.blf', 'NTUSER.DAT{94f431cc-13f9-11f0-9cd6-ef2ce1de21b4}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{94f431cc-13f9-11f0-9cd6-ef2ce1de21b4}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'OneDrive - Amity University', 'photos', 'PrintHood', 'PROJECT 1 DVA', 'Recent', 'sapat', 'sav', 'Saved Games', 'Screenshot_20250712_031717.jpg', 'Screenshot_20250712_031725.jpg', 'Screenshot_20250928_023425.jpg', 'Screenshot_20250928_023438.jpg', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'terasuki.py', 'tex', 'tuchi.ipynb', 'Untitled-1.py', 'Untitled.ipynb', 'untitled.py', 'untitled.txt', 'Untitled1.ipynb', 'untitled1.py', 'untitled1.txt', 'Untitled10.ipynb', 'Untitled11.ipynb', 'Untitled12.ipynb', 'Untitled13.ipynb', 'Untitled14.ipynb', 'Untitled15.ipynb', 'Untitled16.ipynb', 'Untitled17.ipynb', 'Untitled18.ipynb', 'Untitled19.ipynb', 'Untitled2.ipynb', 'untitled2.txt', 'Untitled20.ipynb', 'Untitled21.ipynb', 'Untitled22.ipynb', 'Untitled23.ipynb', 'Untitled24.ipynb', 'Untitled25.ipynb', 'Untitled26.ipynb', 'Untitled27.ipynb', 'Untitled28.ipynb', 'Untitled29.ipynb', 'Untitled3.ipynb', 'Untitled30.ipynb', 'Untitled31.ipynb', 'Untitled32.ipynb', 'Untitled33.ipynb', 'Untitled34.ipynb', 'Untitled35.ipynb', 'Untitled36.ipynb', 'Untitled37.ipynb', 'Untitled38.ipynb', 'Untitled39.ipynb', 'Untitled4.ipynb', 'Untitled40.ipynb', 'Untitled41.ipynb', 'Untitled42.ipynb', 'Untitled43.ipynb', 'Untitled44.ipynb', 'Untitled45.ipynb', 'Untitled46.ipynb', 'Untitled47.ipynb', 'Untitled48.ipynb', 'Untitled49.ipynb', 'Untitled5.ipynb', 'Untitled50.ipynb', 'Untitled51.ipynb', 'Untitled52.ipynb', 'Untitled53.ipynb', 'Untitled54.ipynb', 'Untitled55.ipynb', 'Untitled56.ipynb', 'Untitled57.ipynb', 'Untitled58.ipynb', 'Untitled59.ipynb', 'Untitled6.ipynb', 'Untitled60.ipynb', 'Untitled61.ipynb', 'Untitled62.ipynb', 'Untitled63.ipynb', 'Untitled64.ipynb', 'Untitled65.ipynb', 'Untitled66.ipynb', 'Untitled67.ipynb', 'Untitled68.ipynb', 'Untitled69.ipynb', 'Untitled7.ipynb', 'Untitled70.ipynb', 'Untitled71.ipynb', 'Untitled72.ipynb', 'Untitled73.ipynb', 'Untitled74.ipynb', 'Untitled75.ipynb', 'Untitled76.ipynb', 'Untitled77.ipynb', 'Untitled78.ipynb', 'Untitled79.ipynb', 'Untitled8.ipynb', 'Untitled80.ipynb', 'Untitled81.ipynb', 'Untitled82.ipynb', 'Untitled83.ipynb', 'Untitled84.ipynb', 'Untitled85.ipynb', 'Untitled86.ipynb', 'Untitled87.ipynb', 'Untitled88.ipynb', 'Untitled89.ipynb', 'Untitled9.ipynb', 'Untitled90.ipynb', 'Videos']

In [1]:
import pandas as pd
import numpy as np

In [2]:
orders = pd.read_csv("orders.csv")
people = pd.read_csv("people.csv")
returns = pd.read_csv("returns.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'orders.csv'

In [3]:
import os
print(os.getcwd())

C:\Users\Drrajan04

In [4]:
os.chdir(r"C:\Users\Drrajan04\Downloads")

In [5]:
orders = pd.read_csv("orders.csv")
people = pd.read_csv("people.csv")
returns = pd.read_csv("returns.csv")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 6512: invalid continuation byte

In [6]:
orders = pd.read_csv("orders.csv", encoding="latin1")
people = pd.read_csv("people.csv", encoding="latin1")
returns = pd.read_csv("returns.csv", encoding="latin1")

In [7]:
orders.head()
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  object
 3   Ship Date       51290 non-null  object
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   Postal Code     9994 non-null   float64
 9   City            51290 non-null  object
 10  State           51290 non-null  object
 11  Country         51290 non-null  object
 12  Region          51290 non-null  object
 13  Market          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Product Name    51290 non-null  object
 18  Sales           51290 non-null  object
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  object
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: float64(3), int64(2), object(19)
memory usage: 9.4+ MB

In [8]:
orders.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
Postal Code       41296
City                  0
State                 0
Country               0
Region                0
Market                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [9]:
orders.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,11-11-2014,13-11-2014,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,$221.98,2,0.0,$62.15,40.77,High
1,26341,IN-2014-JR162107-41675,05-02-2014,07-02-2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,-$288.77,923.63,Critical
2,25330,IN-2014-CR127307-41929,17-10-2014,18-10-2014,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$5,175.17",9,0.1,$919.97,915.49,Medium
3,13524,ES-2014-KM1637548-41667,28-01-2014,30-01-2014,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless","$2,892.51",5,0.1,-$96.54,910.16,Medium
4,47221,SG-2014-RH9495111-41948,05-11-2014,06-11-2014,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed","$2,832.96",8,0.0,$311.52,903.04,Critical

In [10]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  object
 3   Ship Date       51290 non-null  object
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   Postal Code     9994 non-null   float64
 9   City            51290 non-null  object
 10  State           51290 non-null  object
 11  Country         51290 non-null  object
 12  Region          51290 non-null  object
 13  Market          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Product Name    51290 non-null  object
 18  Sales           51290 non-null  object
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  object
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: float64(3), int64(2), object(19)
memory usage: 9.4+ MB

In [11]:
orders.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
Postal Code       41296
City                  0
State                 0
Country               0
Region                0
Market                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [12]:
orders.describe()

            Row ID   Postal Code      Quantity      Discount  Shipping Cost
count  51290.00000   9994.000000  51290.000000  51290.000000   51290.000000
mean   25645.50000  55190.379428      3.476545      0.142908      26.478567
std    14806.29199  32063.693350      2.278766      0.212280      57.251373
min        1.00000   1040.000000      1.000000      0.000000       1.002000
25%    12823.25000  23223.000000      2.000000      0.000000       2.610000
50%    25645.50000  56430.500000      3.000000      0.000000       7.790000
75%    38467.75000  90008.000000      5.000000      0.200000      24.450000
max    51290.00000  99301.000000     14.000000      0.850000     933.570000

In [13]:
orders.columns = (
    orders.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

In [14]:
people.columns = (
    people.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

In [15]:
returns.columns = (
    returns.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

In [16]:
# 1. Standardize column names
orders.columns = (
    orders.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

# 2. Convert dates
orders["order_date"] = pd.to_datetime(orders["order_date"], dayfirst=True)
orders["ship_date"] = pd.to_datetime(orders["ship_date"], dayfirst=True)

# 3. Clean currency columns
orders["sales"] = (
    orders["sales"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "")
    .astype(float)
)

orders["profit"] = (
    orders["profit"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "")
    .astype(float)
)

In [17]:
orders.info()
orders.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   row_id          51290 non-null  int64
 1   order_id        51290 non-null  object
 2   order_date      51290 non-null  datetime64[ns]
 3   ship_date       51290 non-null  datetime64[ns]
 4   ship_mode       51290 non-null  object
 5   customer_id     51290 non-null  object
 6   customer_name   51290 non-null  object
 7   segment         51290 non-null  object
 8   postal_code     9994 non-null   float64
 9   city            51290 non-null  object
 10  state           51290 non-null  object
 11  country         51290 non-null  object
 12  region          51290 non-null  object
 13  market          51290 non-null  object
 14  product_id      51290 non-null  object
 15  category        51290 non-null  object
 16  sub_category    51290 non-null  object
 17  product_name    51290 non-null  object
 18  sales           51290 non-null  float64
 19  quantity        51290 non-null  int64
 20  discount        51290 non-null  float64
 21  profit          51290 non-null  float64
 22  shipping_cost   51290 non-null  float64
 23  order_priority  51290 non-null  object
dtypes: datetime64[ns](2), float64(5), int64(2), object(15)
memory usage: 9.4+ MB

,row_id,order_date,ship_date,postal_code,sales,quantity,discount,profit,shipping_cost
count,51290.00000,51290,51290,9994.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,25645.50000,2014-05-11 21:26:49.155780608,2014-05-15 20:42:42.745174528,55190.379428,246.490685,3.476545,0.142908,28.610970,26.478567
min,1.00000,2012-01-01 00:00:00,2012-01-03 00:00:00,1040.000000,0.440000,1.000000,0.000000,-6599.980000,1.002000
25%,12823.25000,2013-06-19 00:00:00,2013-06-23 00:00:00,23223.000000,30.762500,2.000000,0.000000,0.000000,2.610000
50%,25645.50000,2014-07-08 00:00:00,2014-07-12 00:00:00,56430.500000,85.055000,3.000000,0.000000,9.240000,7.790000
75%,38467.75000,2015-05-22 00:00:00,2015-05-26 00:00:00,90008.000000,251.055000,5.000000,0.200000,36.810000,24.450000
max,51290.00000,2015-12-31 00:00:00,2016-01-07 00:00:00,99301.000000,22638.480000,14.000000,0.850000,8399.980000,933.570000
std,14806.29199,NaN,NaN,32063.693350,487.565388,2.278766,0.212280,174.341066,57.251373

In [18]:
orders["delivery_days"] = (
    orders["ship_date"] - orders["order_date"]
).dt.days

In [19]:
orders["profit_margin"] = orders["profit"] / orders["sales"]

In [20]:
orders["order_year"] = orders["order_date"].dt.year
orders["order_month"] = orders["order_date"].dt.month
orders["order_month_name"] = orders["order_date"].dt.month_name()

In [21]:
orders[[
    "order_date",
    "ship_date",
    "delivery_days",
    "sales",
    "profit",
    "profit_margin"
]].head()

  order_date  ship_date  delivery_days    sales  profit  profit_margin
0 2014-11-11 2014-11-13              2   221.98   62.15       0.279980
1 2014-02-05 2014-02-07              2  3709.40 -288.77      -0.077848
2 2014-10-17 2014-10-18              1  5175.17  919.97       0.177766
3 2014-01-28 2014-01-30              2  2892.51  -96.54      -0.033376
4 2014-11-05 2014-11-06              1  2832.96  311.52       0.109963

In [22]:
orders.groupby(["category", "sub_category"])["profit"].sum().sort_values()

category         sub_category
Furniture        Tables          -64083.55
Office Supplies  Fasteners        13844.08
                 Labels           14988.80
                 Supplies         22559.04
                 Envelopes        28849.26
Furniture        Furnishings      46845.56
Office Supplies  Art              57829.90
                 Paper            58111.27
Technology       Machines         58867.70
Office Supplies  Binders          72432.92
                 Storage         108416.94
Technology       Accessories     129626.44
Furniture        Chairs          140396.24
Office Supplies  Appliances      141562.63
Furniture        Bookcases       161924.37
Technology       Phones          216717.44
                 Copiers         258567.63
Name: profit, dtype: float64

In [23]:
orders.groupby("region")[["sales", "profit"]].sum().sort_values("profit")

                        sales     profit
region
Western Asia        317106.95  -53921.70
Western Africa      173878.93  -50408.25
Central Asia         19311.48   -7282.06
Canada               66928.17   17817.39
Southeastern Asia   884423.95   17852.34
Eastern Africa      127856.06   21900.87
Southern Africa     105191.76   24158.55
South America       617223.64   28090.48
Caribbean           324280.89   34571.35
Central Africa      143630.01   35383.71
Central US          501239.88   39706.44
Southern US         391721.90   46749.69
North Africa        233216.61   57836.25
Southern Europe     608594.14   70109.35
Eastern Europe      310033.44   77084.88
Northern Europe     636779.95   83923.29
Eastern US          678781.36   91522.80
Western US          725457.93  108418.69
Oceania            1100185.69  120089.66
Central America    1223100.79  158981.81
Southern Asia       866573.05  159336.18
Eastern Asia        855059.62  167101.62
Western Europe     1731931.05  218433.33

In [24]:
orders.groupby("discount")[["sales", "profit"]].mean()

               sales       profit
discount
0.000     241.042813    61.039522
0.002     567.018872   125.762820
0.070     810.779133   140.990133
0.100     388.300887    63.683658
0.150     565.674954    50.602736
0.170     336.597701    38.317184
0.200     240.862807    23.552765
0.202     395.503902   -14.518537
0.250     444.725404     4.043636
0.270     230.287861    -4.317268
0.300     555.682971   -57.899765
0.320     536.794444   -88.561481
0.350     784.479918  -116.144754
0.370     427.271081   -78.461892
0.400     176.117460   -45.246623
0.402     324.364327  -109.907981
0.450     102.114037   -41.611468
0.470     115.078993   -42.982400
0.500     198.489455   -97.141298
0.550     630.866000  -315.068000
0.570     678.733333  -526.129167
0.600      92.014831   -81.732188
0.602     216.399130  -213.279130
0.650     387.048235  -365.998824
0.700      78.260073  -104.339955
0.800      64.757152  -122.203513
0.850     398.420000 -1534.330000

In [25]:
orders[orders["sub_category"] == "Tables"][
    ["sales", "profit", "discount", "shipping_cost"]
].describe()

             sales       profit    discount  shipping_cost
count   861.000000   861.000000  861.000000     861.000000
mean    879.259199   -74.429210    0.290732      92.756555
std     796.402515   402.974096    0.220513     113.654723
min      24.370000 -2750.280000    0.000000       1.160000
25%     330.590000  -205.610000    0.200000      28.240000
50%     629.060000   -34.650000    0.300000      56.380000
75%    1114.270000   103.040000    0.450000     109.860000
max    5451.300000  2071.440000    0.850000     878.380000

In [26]:
orders.groupby("sub_category")[["discount", "shipping_cost"]].mean().sort_values("shipping_cost", ascending=False)

              discount  shipping_cost
sub_category
Tables        0.290732      92.756555
Copiers       0.117147      71.750430
Bookcases     0.153758      64.491069
Appliances    0.142078      62.174366
Phones        0.145847      55.094874
Machines      0.169583      53.263693
Chairs        0.163110      47.831494
Accessories   0.120481      27.184499
Storage       0.138540      23.924312
Furnishings   0.150628      12.993550
Supplies      0.128043      10.365944
Art           0.117574       8.612065
Binders       0.179284       8.098455
Envelopes     0.132891       7.785072
Paper         0.110109       7.693037
Fasteners     0.137193       3.960042
Labels        0.120527       3.398972

In [27]:
orders_returns = orders.merge(
    returns,
    on="order_id",
    how="left"
)

orders_returns["is_returned"] = orders_returns["returned"].notna()

orders_returns.groupby("sub_category")["is_returned"].mean().sort_values(ascending=False)

sub_category
Labels         0.052672
Tables         0.047619
Accessories    0.044878
Art            0.044613
Copiers        0.044534
Binders        0.043768
Phones         0.043193
Bookcases      0.043136
Paper          0.042955
Chairs         0.042807
Furnishings    0.042803
Supplies       0.042792
Machines       0.042396
Storage        0.041989
Envelopes      0.041475
Fasteners      0.039216
Appliances     0.033869
Name: is_returned, dtype: float64

In [28]:
orders.to_csv("orders_cleaned.csv", index=False)
people.to_csv("people_cleaned.csv", index=False)
returns.to_csv("returns_cleaned.csv", index=False)

In [29]:
pd.read_csv("orders_cleaned.csv").head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,postal_code,city,...,quantity,discount,profit,shipping_cost,order_priority,delivery_days,profit_margin,order_year,order_month,order_month_name
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,2,0.0,62.15,40.77,High,2,0.279980,2014,11,November
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,9,0.1,-288.77,923.63,Critical,2,-0.077848,2014,2,February
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,9,0.1,919.97,915.49,Medium,1,0.177766,2014,10,October
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,5,0.1,-96.54,910.16,Medium,2,-0.033376,2014,1,January
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,8,0.0,311.52,903.04,Critical,1,0.109963,2014,11,November

In [1]:
# ====================== ADVANCED ANALYSIS - A/B TESTING + ML ======================

import pandas as pd
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error
import matplotlib.pyplot as plt


df = pd.read_csv('retail_data.csv')         

print(" Data loaded! Total rows:", df.shape[0])

# ====================== PART 1: A/B TESTING ======================
print("\n=== A/B Testing: Does discount >20% hurt profit? ===")

df['Discount_Group'] = df['Discount'].apply(lambda x: 'High (>20%)' if x > 0.20 else 'Low (≤20%)')

group_high = df[df['Discount_Group'] == 'High (>20%)']['Profit']
group_low  = df[df['Discount_Group'] == 'Low (≤20%)']['Profit']

t_stat, p_value = stats.ttest_ind(group_high, group_low)

print(f"p-value: {p_value:.4f}")
if p_value < 0.05:
    print(" Result: High discount (>20%) has statistically significant negative impact on profit!")
else:
    print("Result: No significant difference.")

# ====================== PART 2: BASIC ML (Linear Regression) ======================
print("\n=== Basic ML: Predicting Profit ===")

features = ['Sales', 'Quantity', 'Discount']
X = df[features]
y = df['Profit']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"Model Accuracy (R²): {r2:.3f}")
print(f"Mean Absolute Error: ₹{mae:.2f}")

# Show which features affect profit
coeff = pd.DataFrame({
    'Feature': features,
    'Impact on Profit (₹)': model.coef_
})
print(coeff)

FileNotFoundError: [Errno 2] No such file or directory: 'retail_data.csv'

In [2]:
import os
print("Files in current folder:")
print(os.listdir())

Files in current folder:
['.anaconda', '.conda', '.condarc', '.continuum', '.ipynb_checkpoints', '.ipython', '.jupyter', '.matplotlib', '.virtual_documents', '.vscode', '01_data_cleaning_eda.ipynb', '01_data_understanding.ipynb', '3D Objects', 'anaconda3', 'anaconda_projects', 'AppData', 'Application Data', 'bich.py', 'BullseyeCoverageError.txt', 'Contacts', 'Cookies', 'Desktop', 'Documents', 'Downloads', 'dva project 2 sample.ipynb', 'Favorites', 'hes.ipynb', 'IntelGraphicsProfiles', 'Links', 'Local Settings', 'Microsoft', 'MicrosoftEdgeBackups', 'mod', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{94f431cb-13f9-11f0-9cd6-ef2ce1de21b4}.TxR.0.regtrans-ms', 'NTUSER.DAT{94f431cb-13f9-11f0-9cd6-ef2ce1de21b4}.TxR.1.regtrans-ms', 'NTUSER.DAT{94f431cb-13f9-11f0-9cd6-ef2ce1de21b4}.TxR.2.regtrans-ms', 'NTUSER.DAT{94f431cb-13f9-11f0-9cd6-ef2ce1de21b4}.TxR.blf', 'NTUSER.DAT{94f431cc-13f9-11f0-9cd6-ef2ce1de21b4}.TM.blf', 'NTUSER.DAT{94f431cc-13f9-11f0-9cd6-ef2ce1de21b4}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{94f431cc-13f9-11f0-9cd6-ef2ce1de21b4}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'OneDrive - Amity University', 'photos', 'PrintHood', 'PROJECT 1 DVA', 'Recent', 'sapat', 'sav', 'Saved Games', 'Screenshot_20250712_031717.jpg', 'Screenshot_20250712_031725.jpg', 'Screenshot_20250928_023425.jpg', 'Screenshot_20250928_023438.jpg', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'terasuki.py', 'tex', 'tuchi.ipynb', 'Untitled-1.py', 'Untitled.ipynb', 'untitled.py', 'untitled.txt', 'Untitled1.ipynb', 'untitled1.py', 'untitled1.txt', 'Untitled10.ipynb', 'Untitled11.ipynb', 'Untitled12.ipynb', 'Untitled13.ipynb', 'Untitled14.ipynb', 'Untitled15.ipynb', 'Untitled16.ipynb', 'Untitled17.ipynb', 'Untitled18.ipynb', 'Untitled19.ipynb', 'Untitled2.ipynb', 'untitled2.txt', 'Untitled20.ipynb', 'Untitled21.ipynb', 'Untitled22.ipynb', 'Untitled23.ipynb', 'Untitled24.ipynb', 'Untitled25.ipynb', 'Untitled26.ipynb', 'Untitled27.ipynb', 'Untitled28.ipynb', 'Untitled29.ipynb', 'Untitled3.ipynb', 'Untitled30.ipynb', 'Untitled31.ipynb', 'Untitled32.ipynb', 'Untitled33.ipynb', 'Untitled34.ipynb', 'Untitled35.ipynb', 'Untitled36.ipynb', 'Untitled37.ipynb', 'Untitled38.ipynb', 'Untitled39.ipynb', 'Untitled4.ipynb', 'Untitled40.ipynb', 'Untitled41.ipynb', 'Untitled42.ipynb', 'Untitled43.ipynb', 'Untitled44.ipynb', 'Untitled45.ipynb', 'Untitled46.ipynb', 'Untitled47.ipynb', 'Untitled48.ipynb', 'Untitled49.ipynb', 'Untitled5.ipynb', 'Untitled50.ipynb', 'Untitled51.ipynb', 'Untitled52.ipynb', 'Untitled53.ipynb', 'Untitled54.ipynb', 'Untitled55.ipynb', 'Untitled56.ipynb', 'Untitled57.ipynb', 'Untitled58.ipynb', 'Untitled59.ipynb', 'Untitled6.ipynb', 'Untitled60.ipynb', 'Untitled61.ipynb', 'Untitled62.ipynb', 'Untitled63.ipynb', 'Untitled64.ipynb', 'Untitled65.ipynb', 'Untitled66.ipynb', 'Untitled67.ipynb', 'Untitled68.ipynb', 'Untitled69.ipynb', 'Untitled7.ipynb', 'Untitled70.ipynb', 'Untitled71.ipynb', 'Untitled72.ipynb', 'Untitled73.ipynb', 'Untitled74.ipynb', 'Untitled75.ipynb', 'Untitled76.ipynb', 'Untitled77.ipynb', 'Untitled78.ipynb', 'Untitled79.ipynb', 'Untitled8.ipynb', 'Untitled80.ipynb', 'Untitled81.ipynb', 'Untitled82.ipynb', 'Untitled83.ipynb', 'Untitled84.ipynb', 'Untitled85.ipynb', 'Untitled86.ipynb', 'Untitled87.ipynb', 'Untitled88.ipynb', 'Untitled89.ipynb', 'Untitled9.ipynb', 'Untitled90.ipynb', 'Videos']

In [1]:
# ====================== ADVANCED ANALYSIS - A/B TESTING + BASIC ML ======================
import pandas as pd
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error
import matplotlib.pyplot as plt

# Load your real data file
df = pd.read_csv('orders_cleaned.csv')

print(" SUCCESS! Data loaded.")
print("Total rows:", df.shape[0])
print("\nFirst 5 rows preview:")
print(df.head())

# ====================== PART 1: A/B TESTING ======================
print("\n=== A/B Testing: High Discount vs Low Discount on Profit ===")

df['Discount_Group'] = df['Discount'].apply(lambda x: 'High (>20%)' if x > 0.20 else 'Low (≤20%)')

group_high = df[df['Discount_Group'] == 'High (>20%)']['Profit']
group_low  = df[df['Discount_Group'] == 'Low (≤20%)']['Profit']

t_stat, p_value = stats.ttest_ind(group_high, group_low)

print(f"p-value: {p_value:.4f}")
if p_value < 0.05:
    print("High discount (>20%) has statistically significant negative impact on profit!")
else:
    print("Result: No significant difference.")

# ====================== PART 2: BASIC ML (Linear Regression) ======================
print("\n=== Basic ML: Predicting Profit ===")

features = ['Sales', 'Quantity', 'Discount']
X = df[features]
y = df['Profit']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"Model Accuracy (R²): {r2:.3f}")
print(f"Mean Absolute Error: ₹{mae:.2f}")

coeff = pd.DataFrame({
    'Feature': features,
    'Impact on Profit (₹)': model.coef_
})
print("\nFeature Impact:")
print(coeff)

FileNotFoundError: [Errno 2] No such file or directory: 'orders_cleaned.csv'

In [3]:
# ====================== ADVANCED ANALYSIS - A/B TESTING + BASIC ML ======================
import pandas as pd
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error
import matplotlib.pyplot as plt

# Load your real data file
df = pd.read_csv(r'C:\Users\Drrajan04\OneDrive\Desktop\orders_cleaned.csv')

print("SUCCESS! Data loaded.")
print("Total rows:", df.shape[0])
print("\nFirst 5 rows preview:")
print(df.head())

# ====================== PART 1: A/B TESTING ======================
print("\n=== A/B Testing: High Discount vs Low Discount on Profit ===")

df['Discount_Group'] = df['Discount'].apply(lambda x: 'High (>20%)' if x > 0.20 else 'Low (≤20%)')

group_high = df[df['Discount_Group'] == 'High (>20%)']['Profit']
group_low  = df[df['Discount_Group'] == 'Low (≤20%)']['Profit']

t_stat, p_value = stats.ttest_ind(group_high, group_low)

print(f"p-value: {p_value:.4f}")
if p_value < 0.05:
    print(" High discount (>20%) has statistically significant negative impact on profit!")
else:
    print("Result: No significant difference.")

# ====================== PART 2: BASIC ML (Linear Regression) ======================
print("\n=== Basic ML: Predicting Profit ===")

features = ['Sales', 'Quantity', 'Discount']
X = df[features]
y = df['Profit']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"Model Accuracy (R²): {r2:.3f}")
print(f"Mean Absolute Error: ₹{mae:.2f}")

coeff = pd.DataFrame({
    'Feature': features,
    'Impact on Profit (₹)': model.coef_
})
print("\nFeature Impact:")
print(coeff)

SUCCESS! Data loaded.
Total rows: 51290

First 5 rows preview:
   row_id                  order_id  order_date   ship_date     ship_mode  \
0   40098  CA-2014-AB10015140-41954  2014-11-11  2014-11-13   First Class
1   26341    IN-2014-JR162107-41675  2014-02-05  2014-02-07  Second Class
2   25330    IN-2014-CR127307-41929  2014-10-17  2014-10-18   First Class
3   13524   ES-2014-KM1637548-41667  2014-01-28  2014-01-30   First Class
4   47221   SG-2014-RH9495111-41948  2014-11-05  2014-11-06      Same Day

    customer_id     customer_name      segment  postal_code           city  \
0  AB-100151402     Aaron Bergman     Consumer      73120.0  Oklahoma City
1     JR-162107     Justin Ritter    Corporate          NaN     Wollongong
2     CR-127307      Craig Reiter     Consumer          NaN       Brisbane
3    KM-1637548  Katherine Murray  Home Office          NaN         Berlin
4    RH-9495111       Rick Hansen     Consumer          NaN          Dakar

   ... quantity discount  profit shipping_cost order_priority delivery_days  \
0  ...        2      0.0   62.15         40.77           High             2
1  ...        9      0.1 -288.77        923.63       Critical             2
2  ...        9      0.1  919.97        915.49         Medium             1
3  ...        5      0.1  -96.54        910.16         Medium             2
4  ...        8      0.0  311.52        903.04       Critical             1

  profit_margin order_year  order_month  order_month_name
0      0.279980       2014           11          November
1     -0.077848       2014            2          February
2      0.177766       2014           10           October
3     -0.033376       2014            1           January
4      0.109963       2014           11          November

[5 rows x 29 columns]

=== A/B Testing: High Discount vs Low Discount on Profit ===

KeyError: 'Discount'

In [4]:
# ====================== ADVANCED ANALYSIS - A/B TESTING + BASIC ML ======================
import pandas as pd
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error
import matplotlib.pyplot as plt

# Load your data
df = pd.read_csv(r'C:\Users\Drrajan04\OneDrive\Desktop\orders_cleaned.csv')

print("Data loaded successfully!")
print("Total rows:", df.shape[0])

# ====================== PART 1: A/B TESTING ======================
print("\n=== A/B Testing: High Discount (>20%) vs Low Discount on Profit ===")

df['Discount_Group'] = df['discount'].apply(lambda x: 'High (>20%)' if x > 0.20 else 'Low (≤20%)')

group_high = df[df['Discount_Group'] == 'High (>20%)']['profit']
group_low  = df[df['Discount_Group'] == 'Low (≤20%)']['profit']

t_stat, p_value = stats.ttest_ind(group_high, group_low)

print(f"p-value: {p_value:.4f}")
if p_value < 0.05:
    print("High discount (>20%) has statistically significant negative impact on profit!")
else:
    print("Result: No significant difference.")

# ====================== PART 2: BASIC ML (Linear Regression) ======================
print("\n=== Basic ML: Predicting Profit ===")

features = ['sales', 'quantity', 'discount']
X = df[features]
y = df['profit']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"Model Accuracy (R²): {r2:.3f}")
print(f"Mean Absolute Error: ₹{mae:.2f}")

coeff = pd.DataFrame({
    'Feature': features,
    'Impact on Profit (₹)': model.coef_
})
print("\nFeature Impact:")
print(coeff)

Data loaded successfully!
Total rows: 51290

=== A/B Testing: High Discount (>20%) vs Low Discount on Profit ===
p-value: 0.0000
High discount (>20%) has statistically significant negative impact on profit!

=== Basic ML: Predicting Profit ===
Model Accuracy (R²): 0.261
Mean Absolute Error: ₹60.28

Feature Impact:
    Feature  Impact on Profit (₹)
0     sales              0.178375
1  quantity             -4.280287
2  discount           -226.657010